#### Extended Figure 6e — GSEA running-enrichment curves (2x2) ####
#
# Panel:   Ext Fig 6e. Base-graphics 2x2 grid: rows = centrality axis
#          (triplet_pairs, cum_abs_estimate_total), columns = gene set
#          (expressed enhancers, mediating enhancers). Each panel shows the
#          running enrichment-score curve -- whether enhancers in that gene
#          set are concentrated near the top of the ranking by that
#          centrality axis -- (subsampled to ~4000 points by the
#          regeneration script) with a rug of hit positions, NES/FDR
#          annotation, coloured red (NES>0, enrichment toward high-centrality
#          enhancers) or blue (NES<0, enrichment toward low-centrality ones).
# Reads:   Fig6/data/gsea_results.csv, gsea_running_curves.csv,
#          gsea_hit_positions.csv
#          (regenerated by
#           ../Data_and_code/screen_correlation/build_screen_analyses_data.R)
# Writes:  Fig6/out/ext_f6e.gsea_enrichment_plots.{png,pdf}
#
# Note: this panel is rendered with base R graphics, not ggplot2, so
# bimodal_theme does not apply directly -- font family/sizes are set via
# par(family=) and cex instead, matching the 5-7pt Arial convention.

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

gsea_df <- read.csv(paste0(path_fig6_data, 'gsea_results.csv'), stringsAsFactors = FALSE)
curves  <- read.csv(paste0(path_fig6_data, 'gsea_running_curves.csv'), stringsAsFactors = FALSE)
hits_df <- read.csv(paste0(path_fig6_data, 'gsea_hit_positions.csv'), stringsAsFactors = FALSE)

axis_labels  <- c(triplet_pairs = 'Rank (triplet-pair count)',
                  cum_abs_estimate_total = 'Rank (cumulative |estimate|)')
panel_labels <- c(expressed_TRUE = 'Expressed enhancers',
                  mediating_TRUE = 'Mediating enhancers')
plot_sets <- c('expressed_TRUE', 'mediating_TRUE')
axes_names <- c('triplet_pairs', 'cum_abs_estimate_total')

draw_gsea_grid <- function() {
  par(mfrow = c(2, 2), mar = c(3, 3, 2.5, 1), mgp = c(1.8, 0.5, 0),
      family = 'Arial', cex.axis = 0.7, cex.lab = 0.8)

  for (axis_name in axes_names) {
    for (gs_name in plot_sets) {

      row <- gsea_df[gsea_df$axis == axis_name & gsea_df$gene_set == gs_name, ]
      fdr_label <- if (nrow(row) == 0) {
                     'FDR=NA'
                   } else if (!row$meaningful) {
                     'FDR=N/A (trivial)'
                   } else if (!is.na(row$fdr)) {
                     paste0('FDR=', signif(row$fdr, 2))
                   } else 'FDR=NA'
      nes_label <- if (nrow(row) > 0 && !is.na(row$NES))
                     paste0('NES=', round(row$NES, 2)) else ''

      cv <- curves[curves$axis == axis_name & curves$gene_set == gs_name, ]
      hp <- hits_df[hits_df$axis == axis_name & hits_df$gene_set == gs_name, ]

      if (nrow(cv) == 0) { plot.new(); next }

      col_curve <- if (nrow(row) > 0 && !is.na(row$NES) && row$NES > 0) '#B2182B' else '#2166AC'
      ylim_range <- range(cv$es)
      if (diff(ylim_range) < 0.01) ylim_range <- c(-0.05, 0.05)

      plot(cv$rank, cv$es, type = 'l', col = col_curve, lwd = 1.2,
           ylim = ylim_range,
           xlab = axis_labels[axis_name], ylab = 'Enrichment score',
           main = panel_labels[gs_name], cex.main = 0.8)
      abline(h = 0, col = 'grey60', lty = 2)
      if (nrow(hp) > 0) rug(hp$rank, col = col_curve, ticksize = 0.05, quiet = TRUE)
      mtext(paste(nes_label, fdr_label, sep = '  '), side = 3, line = 0,
            cex = 0.6,
            col = if (nrow(row) > 0 && !is.na(row$fdr) && row$fdr < 0.05) 'red3' else 'grey30')
    }
  }
}

save_grid_png_pdf(draw_gsea_grid, path_fig6, 'ext_f6e.gsea_enrichment_plots',
                  width_in = 4.6, height_in = 4.6)
