#### Extended Figure 6d — new-route triplet counts by TF and by target gene ####
#
# Panel:   Ext Fig 6d. Two stacked bar charts in one figure:
#            top    - top 20 TFs by number of entirely new tCRE routes
#            bottom - top 20 target genes gaining the most new tCRE routes
#          A "new route" is a complete TF -> enhancer(tCRE) -> promoter
#          triplet whose TF/promoter pair is absent from the aCRE-only
#          network -- i.e. modelling the enhancer's own transcriptional
#          activity creates a regulatory path that chromatin accessibility
#          alone would have missed entirely.
# Reads:   Fig6/data/triplets_tCRE.csv
#          (regenerated by
#           ../Data_and_code/tCRE_topology/build_tCRE_topology_data.R, which
#           also resolves the `gene` column via its promoter_gene_lookup)
# Writes:  Fig6/out/ext_f6d.new_route_triplet_bars_TF_and_target.{png,pdf}

library(ggplot2)
library(patchwork)

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

triplets_tCRE      <- read.csv(paste0(path_fig6_data, 'triplets_tCRE.csv'))
new_route_triplets <- triplets_tCRE[triplets_tCRE$new_route, ]

message('New-route triplets: ', nrow(new_route_triplets))

#### Top 20 TFs by new-route triplet count ####

tf_counts <- sort(table(new_route_triplets$TF), decreasing = TRUE)
n_tf      <- min(20, length(tf_counts))
tf_bar_df <- data.frame(
  TF    = factor(names(tf_counts)[seq_len(n_tf)],
                 levels = rev(names(tf_counts)[seq_len(n_tf)])),
  count = as.integer(tf_counts)[seq_len(n_tf)]
)

p_tf <- ggplot(tf_bar_df, aes(x = TF, y = count)) +
  geom_bar(stat = 'identity', fill = 'steelblue') +
  coord_flip() +
  scale_y_continuous(name = 'Number of new-route tCRE triplets',
                     expand = expansion(mult = c(0, 0.08))) +
  scale_x_discrete(name = '') +
  ggtitle('Top 20 TFs by number of entirely new tCRE routes') +
  bimodal_theme +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(colour = 'grey92'))

#### Top 20 target genes by new-route triplet count ####

gene_counts <- sort(table(new_route_triplets$gene), decreasing = TRUE)
n_gene      <- min(20, length(gene_counts))
gene_bar_df <- data.frame(
  gene  = factor(names(gene_counts)[seq_len(n_gene)],
                 levels = rev(names(gene_counts)[seq_len(n_gene)])),
  count = as.integer(gene_counts)[seq_len(n_gene)]
)

p_gene <- ggplot(gene_bar_df, aes(x = gene, y = count)) +
  geom_bar(stat = 'identity', fill = 'darkorange') +
  coord_flip() +
  scale_y_continuous(name = 'Number of new-route tCRE triplets',
                     expand = expansion(mult = c(0, 0.08))) +
  scale_x_discrete(name = '') +
  ggtitle('Top 20 target genes gaining the most new tCRE routes') +
  bimodal_theme +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(colour = 'grey92'))

ext_f6d <- p_tf / p_gene

save_panel_png_pdf(ext_f6d, path_fig6,
                   'ext_f6d.new_route_triplet_bars_TF_and_target',
                   width_in = 3.4, height_in = 6.0)
