#### Extended Figure 6e — GSEA running-enrichment curves (2x2) ####
#
# Panel:   Ext Fig 6e. 2x2 grid (top-right cell dropped as uninformative, so
#          3 cells in an L-shape): rows = centrality axis (triplet_pairs,
#          cum_abs_estimate_total), columns = gene set (expressed enhancers,
#          mediating enhancers). Each panel shows the running enrichment-score
#          curve -- whether enhancers in that gene set are concentrated near
#          the top of the ranking by that centrality axis -- (subsampled to
#          ~4000 points by the regeneration script) with a rug of hit
#          positions, NES/FDR annotation, coloured red (NES>0, enrichment
#          toward high-centrality enhancers) or blue (NES<0, enrichment
#          toward low-centrality ones).
# Reads:   Fig6/data/gsea_results.csv, gsea_running_curves.csv,
#          gsea_hit_positions.csv
#          (regenerated by
#           ../Data_and_code/screen_correlation/build_screen_analyses_data.R)
# Writes:  Fig6/out/ext_f6e.gsea_enrichment_plots.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

library(ggplot2)
library(dplyr)
library(patchwork)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

gsea_df <- read.csv(paste0(path_fig6_data, 'gsea_results.csv'), stringsAsFactors = FALSE)
curves  <- read.csv(paste0(path_fig6_data, 'gsea_running_curves.csv'), stringsAsFactors = FALSE)
hits_df <- read.csv(paste0(path_fig6_data, 'gsea_hit_positions.csv'), stringsAsFactors = FALSE)

axis_labels  <- c(triplet_pairs = 'Rank (triplet-pair count)',
                  cum_abs_estimate_total = 'Rank (cumulative |estimate|)')
panel_labels <- c(expressed_TRUE = 'Expressed enhancers',
                  mediating_TRUE = 'Mediating enhancers')
plot_sets <- c('expressed_TRUE', 'mediating_TRUE')
axes_names <- c('triplet_pairs', 'cum_abs_estimate_total')

# One ggplot per (axis, gene_set) cell -- built the same way the previous
# base-R version looped over cells, just returning a grob instead of drawing
# directly, so patchwork can lay out the 2x2 grid with bimodal_theme applied
# uniformly (the base-R version could not use bimodal_theme at all).
make_gsea_cell <- function(axis_name, gs_name) {

  row <- gsea_df[gsea_df$axis == axis_name & gsea_df$gene_set == gs_name, ]
  fdr_label <- if (nrow(row) == 0) {
                 'FDR=NA'
               } else if (!row$meaningful) {
                 'FDR=N/A (trivial)'
               } else if (!is.na(row$fdr)) {
                 paste0('FDR=', signif(row$fdr, 2))
               } else 'FDR=NA'
  nes_label <- if (nrow(row) > 0 && !is.na(row$NES))
                 paste0('NES=', round(row$NES, 2)) else ''
  annotation_colour <- if (nrow(row) > 0 && !is.na(row$fdr) && row$fdr < 0.05)
                         'red3' else 'grey30'

  cv <- curves[curves$axis == axis_name & curves$gene_set == gs_name, ]
  hp <- hits_df[hits_df$axis == axis_name & hits_df$gene_set == gs_name, ]

  if (nrow(cv) == 0) return(patchwork::plot_spacer())

  col_curve <- if (nrow(row) > 0 && !is.na(row$NES) && row$NES > 0) '#B2182B' else '#2166AC'
  ylim_range <- range(cv$es)
  if (diff(ylim_range) < 0.01) ylim_range <- c(-0.05, 0.05)
  rug_y <- ylim_range[1] - 0.05 * diff(ylim_range)

  p <- ggplot(cv, aes(x = rank, y = es)) +
    geom_hline(yintercept = 0, colour = 'grey60', linetype = 'dashed', linewidth = 0.3) +
    geom_line(colour = col_curve, linewidth = 0.5) +
    { if (nrow(hp) > 0)
        geom_segment(data = hp, aes(x = rank, xend = rank, y = rug_y, yend = ylim_range[1]),
                     colour = col_curve, linewidth = 0.2, inherit.aes = FALSE) } +
    annotate('text', x = -Inf, y = Inf, label = paste(nes_label, fdr_label, sep = '  '),
            hjust = -0.05, vjust = 1.4, size = 1.8, colour = annotation_colour,
            family = 'Arial') +
    scale_y_continuous(name = 'Enrichment score',
                       limits = c(rug_y, ylim_range[2] * 1.05)) +
    scale_x_continuous(name = axis_labels[axis_name]) +
    ggtitle(panel_labels[gs_name]) +
    bimodal_theme +
    theme(plot.title = element_text(size = 6, face = 'bold', hjust = 0.5))

  p
}

cells <- lapply(axes_names, function(axis_name)
  lapply(plot_sets, function(gs_name) make_gsea_cell(axis_name, gs_name)))

# Top-right cell (triplet_pairs x mediating_TRUE) dropped as uninformative,
# leaving an L-shaped 3-cell layout: the top row keeps only its left cell,
# the bottom row keeps both.
ext_f6e <- (cells[[1]][[1]] | patchwork::plot_spacer()) /
           (cells[[2]][[1]] | cells[[2]][[2]])

# Sized for the Ext Fig 6 layout (A|B)/C/(D|(E/F)): E sits above F in a
# shared column next to D, tuned together with F to match D's total height
# -- see ext_fig6d_new_route_triplet_bars.R / ext_fig6f_hitscore_sign_triplet_bar.R.
# All 6 Ext Fig 6 panels then scaled by a uniform 0.95 factor (4.0x4.0in ->
# 3.8x3.8in) to fit the full figure within the A4 page height including
# panel letters.
save_panel_png_pdf(ext_f6e, path_fig6, 'ext_f6e.gsea_enrichment_plots',
                   width_in = 3.8, height_in = 3.8)
