#### Extended Figure 6f — triplet participation by hit-score sign ####
#
# Panel:   Ext Fig 6f. Stacked proportion bar: x = hit-score sign
#          (positive/negative, from each enhancer's mean CRISPRi screen hit
#          score for a given differentiation-step contrast), fill = triplet
#          participation (whether the enhancer bridges at least one complete
#          TF -> enhancer -> promoter triplet, triplet_pairs>0 vs =0),
#          faceted by differentiation-step contrast. FDR-annotated Fisher
#          test (triplet participation x hit-score sign) per contrast.
# Reads:   Fig6/data/hitscore_sign_enhancers.csv, hitscore_sign_tests.csv
#          (regenerated by
#           ../Data_and_code/screen_correlation/build_screen_analyses_data.R)
# Writes:  Fig6/out/ext_f6f.hitscore_sign_triplet_bar.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

library(ggplot2)
library(dplyr)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

plot_df  <- read.csv(paste0(path_fig6_data, 'hitscore_sign_enhancers.csv'), stringsAsFactors = FALSE)
tests_df <- read.csv(paste0(path_fig6_data, 'hitscore_sign_tests.csv'), stringsAsFactors = FALSE)

contrast_order <- c('iPSvsNSC_P0', 'NSC_P0vsNSC_P2', 'NSC_P2vsNeuron')
contrast_labels <- c(
  iPSvsNSC_P0    = 'iPS vs NSC P0',
  NSC_P0vsNSC_P2 = 'NSC P0 vs NSC P2',
  NSC_P2vsNeuron = 'NSC P2 vs Neuron'
)

plot_df$contrast_f <- factor(dplyr::recode(plot_df$contrast, !!!contrast_labels),
                             levels = unname(contrast_labels[contrast_order]))

bar_df <- plot_df %>%
  group_by(contrast_f, hit_sign, has_triplet) %>%
  summarise(n = n(), .groups = 'drop')

# Fisher-test FDR annotation per contrast (from precomputed hitscore_sign_tests.csv)
fisher_tests <- tests_df[tests_df$test == 'Fisher: triplet_pairs>0 x hit_score sign', ]
fisher_tests$contrast_f <- factor(dplyr::recode(fisher_tests$contrast, !!!contrast_labels),
                                  levels = unname(contrast_labels[contrast_order]))
fdr_label_df <- fisher_tests %>%
  mutate(label = paste0('FDR=', signif(fdr, 2)))

ext_f6f <- ggplot(bar_df, aes(x = hit_sign, y = n, fill = has_triplet)) +
  geom_col(position = 'fill') +
  facet_wrap(~contrast_f, nrow = 1) +
  geom_text(data = fdr_label_df, aes(x = 1.5, y = 1.05, label = label),
            inherit.aes = FALSE, size = 1.8, family = 'Arial') +
  scale_fill_manual(values = c(`TRUE` = '#B2182B', `FALSE` = 'grey80'),
                    name = 'Triplet participation',
                    labels = c(`TRUE` = 'triplet_pairs > 0', `FALSE` = 'triplet_pairs = 0')) +
  scale_y_continuous(name = 'Proportion', expand = expansion(mult = c(0, 0.14))) +
  coord_cartesian(ylim = c(0, 1.12)) +
  # No title -- the panel letter + figure caption identify it.
  labs(x = 'Hit-score sign') +
  bimodal_theme +
  theme(legend.position = 'bottom',
        legend.key.size = unit(0.25, 'cm'))

# Sized for the Ext Fig 6 layout (A|B)/C/(D|(E/F)): F sits below E in a
# shared column next to D -- see ext_fig6e_gsea_enrichment.R for the height
# split with D. All 6 Ext Fig 6 panels then scaled by a uniform 0.95
# factor (4.0x1.9in -> 3.8x1.8in) to fit the full figure within the A4
# page height including panel letters.
save_panel_png_pdf(ext_f6f, path_fig6, 'ext_f6f.hitscore_sign_triplet_bar',
                   width_in = 3.8, height_in = 1.8)
