#### Extended Figure 6a — TF-set coupling per expressed enhancer vs adjpvalue threshold ####
#
# Panel:   Extended Figure 6a. For each expressed (tCRE) enhancer regulated
#          by TFs at both the chromatin (aCRE) and expression (tCRE) level,
#          the two TF sets are compared with the Jaccard index and bucketed
#          into fully uncoupled (Jaccard=0, disjoint TF sets) / intermediate
#          / fully coupled (Jaccard=1, identical TF sets). Stacked bar shows
#          how this 3-way split shifts as the adjpvalue significance
#          threshold is swept, with total bar height tracking the shrinking
#          number of enhancers that remain eligible for the comparison at
#          each threshold.
# Reads:   Fig6/data/sweep_category_table.csv
#          (regenerated by
#           ../Data_and_code/threshold_sensitivity_sweep/build_sweep_data.R;
#           the shared plotting logic lives in
#           ../Data_and_code/threshold_sensitivity_sweep/plot_stacked_bar_height.R)
# Writes:  Fig6/out/ext_f6a.stacked_TF_enhancer_adjpvalue.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))
source(paste0(path_code, 'threshold_sensitivity_sweep/plot_stacked_bar_height.R'))

category_table <- read.csv(paste0(path_fig6_data, 'sweep_category_table.csv'))

# show_labels = FALSE: at this panel's less-stringent threshold range, 2+
# categories can be simultaneously tiny within the same bar, which no
# per-segment label placement stayed collision-free for -- see
# plot_stacked_bar_height.R's show_labels doc. Exact percentages belong in
# the figure caption instead.
p <- make_stacked_bar_linheight(category_table,
                                theme_name = 'TF_enhancer',
                                sweep_name = 'adjpvalue_threshold',
                                show_labels = FALSE)

# Sized for the Ext Fig 6 layout (A|B)/C/(D|(E/F)): A pairs with B to span
# the full usable A4 width (~7.47in) on their own shared row -- see
# ext_fig6b_stacked_enhancer_devratio.R for B.
save_panel_png_pdf(p, path_fig6, 'ext_f6a.stacked_TF_enhancer_adjpvalue',
                   width_in = 3.68, height_in = 2.6)
