#### Figure 6e — screen hit-score vs enhancer centrality (Spearman heatmap) ####
#
# Panel:   Fig 6e. Tile heatmap of Spearman rho between each scored enhancer's
#          mean CRISPRi screen hit score and each centrality axis (triplet-
#          pair count, cumulative |estimate|), for the three adjacent
#          differentiation-step transitions. Fill = rho on a blue-white-red
#          diverging scale centred at 0; tiles with FDR < 0.05 get a black
#          outline; each tile is labelled with rho and FDR.
# Reads:   Fig6/data/screen_correlation.csv
#          (regenerated by
#           ../Data_and_code/screen_correlation/build_screen_analyses_data.R)
# Writes:  Fig6/out/f6e.screen_correlation_heatmap.{png,pdf}
#
# Font note: this figure is sized for print, so text sizes are kept in the
# 5-7 pt band via bimodal_theme; the tile labels are set to 1.8 (~5 pt).

library(dplyr)
library(ggplot2)

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

analysis <- 'all_edges'

contrast_order  <- c('iPSvsNSC_P0', 'NSC_P0vsNSC_P2', 'NSC_P2vsNeuron')
contrast_labels <- c(iPSvsNSC_P0    = 'iPS vs NSC P0',
                     NSC_P0vsNSC_P2 = 'NSC P0 vs NSC P2',
                     NSC_P2vsNeuron = 'NSC P2 vs Neuron')

cor_res <- read.csv(paste0(path_fig6_data, 'screen_correlation.csv'),
                    stringsAsFactors = FALSE)

message('Tests: ', nrow(cor_res), '  FDR<0.05: ',
        sum(cor_res$fdr < 0.05, na.rm = TRUE), '  n per test: ', cor_res$n[1])

cor_res$contrast_f <- factor(cor_res$contrast, levels = contrast_order)
cor_res$axis_label <- ifelse(cor_res$axis == 'triplet_pairs',
                             'Triplet-pair count', 'Cumulative |estimate|')

f6e <- ggplot(cor_res, aes(x = contrast_f, y = axis_label, fill = rho)) +
  geom_tile(color = 'grey90', linewidth = 0.4) +
  geom_tile(data = filter(cor_res, fdr < 0.05),
            color = 'black', linewidth = 0.6, fill = NA) +
  scale_x_discrete(labels = contrast_labels) +
  scale_fill_gradient2(low = '#2166AC', mid = 'white', high = '#B2182B',
                       midpoint = 0, name = 'Spearman rho') +
  geom_text(aes(label = paste0('rho=', round(rho, 2), '\n',
                               'FDR=', signif(fdr, 2))),
            size = 1.8, family = 'Arial') +
  # No title -- the panel letter + figure caption identify it.
  labs(x = NULL, y = NULL) +
  bimodal_theme +
  theme(axis.text.x     = element_text(angle = 45, hjust = 1),
        panel.grid      = element_blank(),
        panel.border    = element_blank(),
        legend.key.size = unit(0.3, 'cm'))

# Sized for the Fig6 layout (A|B)/(C|D)/E: E gets its own row below (C|D)
# but, unlike A-D, does NOT span the full usable A4 width -- its own
# content (3 columns x 2 rows of tiles) is naturally wide-short and doesn't
# need the extra width -- see
# Data_and_code/README_Fig5_6_ExtFig7_topics.md for the full per-panel size
# table.
save_panel_png_pdf(f6e, path_fig6, 'f6e.screen_correlation_heatmap',
                   width_in = 4.1, height_in = 2.0)
