#### Figure 6c — new-route donut chart for tCRE triplets ####
#
# Panel:   Fig 6c. Two-ring donut over all complete TF -> enhancer(tCRE) ->
#          promoter triplets. Inner ring: new route (TF/promoter pair absent
#          from the aCRE-only network) vs shared with the aCRE network. Outer
#          ring: the top 10 TFs contributing new-route triplets, remainder
#          collapsed into "Other TFs" ("Remaining"), with the shared slice
#          carried through unchanged. The top-10 TFs are labelled directly
#          via leader lines fanning to a vertical list (their share of
#          new-route triplets only); "Remaining" gets its own short callout
#          near its own wedge; the donut's centre hole shows the new-route
#          share of ALL triplets ("TSS only"). Answers: when an enhancer's
#          own transcriptional activity is modelled explicitly, how much of
#          the resulting TF-enhancer-promoter regulatory structure was
#          invisible to a chromatin-accessibility-only view of the genome,
#          and which TFs contribute the most new-route triplets?
# Reads:   Fig6/data/triplets_tCRE.csv
#          (regenerated by
#           ../Data_and_code/tCRE_topology/build_tCRE_topology_data.R)
# Writes:  Fig6/out/f6c.new_route_donut.{png,pdf}
#
# Expected numbers: 3,929 total triplets, 90.3% new route, 9.7% shared,
# "Other TFs"/"Remaining" = 72.1% of new-route triplets.

library(ggplot2)
library(ggforce)

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

triplets_tCRE <- read.csv(paste0(path_fig6_data, 'triplets_tCRE.csv'))

#### Inner ring: new-route vs shared ####

n_new    <- sum(triplets_tCRE$new_route)
n_shared <- sum(!triplets_tCRE$new_route)
n_total  <- nrow(triplets_tCRE)

message('Triplets: ', n_total, '  new route ', round(100 * n_new / n_total, 1),
        '%  shared ', round(100 * n_shared / n_total, 1), '%')

inner_df <- data.frame(
  label = c('New route\n(TSS only)', 'Shared with\nATAC network'),
  count = c(n_new, n_shared),
  frac  = c(n_new / n_total, n_shared / n_total)
)

#### Outer ring: top 10 TFs in new-route triplets ####

top_n_tfs     <- 10
tf_new_counts <- sort(table(triplets_tCRE$TF[triplets_tCRE$new_route]), decreasing = TRUE)
top_tfs       <- names(tf_new_counts)[seq_len(min(top_n_tfs, length(tf_new_counts)))]
n_top         <- as.integer(tf_new_counts[top_tfs])
n_other_new   <- n_new - sum(n_top)

# 'Remaining' matches the reference figure's own wording for the collapsed
# TF wedge (was 'Other TFs' in an earlier version of this panel).
outer_new_df <- data.frame(
  label    = c(top_tfs, 'Remaining'),
  count    = c(n_top, n_other_new),
  category = 'new_route'
)
outer_shared_df <- data.frame(
  label    = 'Shared with\nATAC network',
  count    = n_shared,
  category = 'shared'
)
outer_df      <- rbind(outer_new_df, outer_shared_df)
outer_df$frac <- outer_df$count / n_total

message('  Remaining: ', round(100 * n_other_new / n_new, 1), '% of new-route')

#### Colours ####

tf_colours    <- colorRampPalette(c('#08519c', '#6baed6'))(length(top_tfs) + 1)
outer_colours <- c(tf_colours, 'grey85')
names(outer_colours) <- c(top_tfs, 'Remaining', 'Shared with\nATAC network')
inner_colours <- c('New route\n(TSS only)'     = '#2171b5',
                   'Shared with\nATAC network' = 'grey85')
all_colours   <- c(inner_colours, outer_colours)

#### Arcs ####
# Angles start at the top and proceed clockwise -- see the IMPORTANT note
# below on ggforce::geom_arc_bar()'s actual angle convention, which this
# start/end formula is written against.

make_arc_df <- function(fracs, labels, r0, r1) {
  end_ang   <- pi/2 - cumsum(fracs) * 2 * pi
  start_ang <- c(pi/2, head(end_ang, -1))
  data.frame(
    x0 = 0, y0 = 0, r0 = r0, r = r1,
    start = start_ang, end = end_ang,
    mid   = (start_ang + end_ang) / 2,
    label = labels, frac = fracs,
    stringsAsFactors = FALSE
  )
}

# Grown from the earlier 1.5/2.4/2.6/3.5 now that 'Remaining' no longer
# needs its own far-side callout (see below) -- that freed up the panel's
# left side, which was previously reserved for 'Remaining''s label, so the
# donut itself can be larger within the same saved canvas.
r_inner_in <- 1.9; r_inner_out <- 3.0
r_outer_in <- 3.2; r_outer_out <- 4.3

arc_inner <- make_arc_df(inner_df$frac, inner_df$label, r_inner_in, r_inner_out)
arc_outer <- make_arc_df(outer_df$frac, outer_df$label, r_outer_in, r_outer_out)

#### Leader-line callouts for the top-10 TFs + 'Remaining' ####
# One label per new-route wedge (the 'Shared with ATAC network' wedge is
# not labelled here -- its share is already stated by the centre label
# below, since the two inner-ring slices are complementary).
callout_df <- arc_outer[arc_outer$label != 'Shared with\nATAC network', ]
callout_df$pct_of_newroute <- round(100 * (outer_df$count[match(callout_df$label, outer_df$label)] / n_new), 1)
callout_df$callout_label   <- paste0(callout_df$label, ' ', callout_df$pct_of_newroute, '%')

# IMPORTANT: ggforce::geom_arc_bar()'s start/end angles do NOT follow the
# standard maths convention (angle 0 = right/+x axis, increasing =
# counterclockwise) that cos()/sin() assume. Confirmed empirically by
# rendering isolated single-wedge test cases and reading back their actual
# (x,y) coordinates via ggplot_build(): angle 0 lands at (0,1) -- STRAIGHT
# UP -- and increasing angle moves CLOCKWISE, i.e. x = r*sin(angle),
# y = r*cos(angle) (sin/cos swapped from the naive assumption). Using plain
# cos(mid)/sin(mid) -- tried first -- silently rotates every label ~90
# degrees clockwise from its true wedge, which was the "TF names point to
# the wrong segment" bug: the wedges themselves render correctly (ggforce
# applies its own convention consistently), but labels computed with the
# WRONG convention land next to a different wedge than the one they name.
# 'Remaining' is such a large wedge (72% of new-route triplets) that it
# wraps most of the way around the donut, so its geometric MID angle lands
# on the far (left) side even though the wedge's own END edge -- the one
# bordering ZIC1's thin sliver, where the clockwise sweep closes the circle
# -- sits on the SAME right side as every TF label. Anchoring 'Remaining'
# at its end angle instead of mid (the 10 TF wedges are thin enough that
# mid vs end makes no visible difference for them, so they keep using mid)
# means its leader line can reach the shared label column with a single
# straight line, matching how the TF ones behave, instead of needing to
# detour around the whole donut.
callout_df$anchor_angle <- ifelse(callout_df$label == 'Remaining',
                                  callout_df$end + 0.2, callout_df$mid) # 0.2: magic number 
callout_df$anchor_x <- (r_outer_out + 0.05) * sin(callout_df$anchor_angle)
callout_df$anchor_y <- (r_outer_out + 0.05) * cos(callout_df$anchor_angle)

# Label text for all 11 wedges (10 TFs + 'Remaining') is placed in a clean
# VERTICAL STACK on the SAME (right) side, one fixed row per label, evenly
# spaced -- not at a shared fixed radius along each wedge's own angle
# (fixed-radius placement was tried first and still collided for the 3-4
# wedges whose angles are within ~20 degrees of each other: their
# circumferential gap at any radius stays smaller than the text height
# needed to tell them apart, no matter how far out the radius goes).
# 'Remaining' is anchored at its END angle (see above, right side, same as
# the TF wedges) rather than its far-side mid angle, so its leader line is
# a single straight segment like the others (an earlier version anchored it
# at its mid angle, which put it on the opposite side and needed a whole
# multi-point detour path around the donut to avoid cutting through it).
# 'Remaining''s end-angle anchor_y already comes out lower than every TF
# wedge's own anchor_y (it sits just past NR2F1 going clockwise, on the
# lower-right of the ring), so a plain sort by anchor_y already puts it
# last -- forcing it last explicitly here just makes that guaranteed rather
# than incidental. On top of being last, it also gets an EXTRA gap
# (gap_before_remaining, on top of the regular row_step) below the 10 TF
# rows, so it reads as visually separate from the ranked TF list -- pushed
# further down toward the bottom of the panel per explicit user request,
# rather than sitting right after NR2F1 with the same spacing as every
# other consecutive pair.
callout_df$sort_key <- ifelse(callout_df$label == 'Remaining', -Inf, callout_df$anchor_y)
callout_df <- callout_df[order(callout_df$sort_key, decreasing = TRUE), ]
n_callout <- nrow(callout_df)
row_top   <- r_outer_out + 3.0
row_step  <- 0.62
gap_before_remaining <- 5
row_offset <- (seq_len(n_callout) - 1) * row_step +
  ifelse(callout_df$label == 'Remaining', gap_before_remaining, 0)
callout_df$label_x <- r_outer_out + 1.4
callout_df$label_y <- row_top - row_offset
callout_df$label_hjust <- 0

# Label colour matches its wedge's own fill (as in the reference figure),
# falling back to a dark neutral for the 'Remaining' slice (grey85 fill
# would be unreadable as text colour).
callout_df$text_colour <- ifelse(callout_df$label == 'Remaining', '#2171b5',
                                 unname(outer_colours[callout_df$label]))

#### Centre label: new-route share of ALL triplets ####

centre_label <- paste0('TSS only\n', round(100 * n_new / n_total, 1), '%')

p_donut <- ggplot() +
  ggforce::geom_arc_bar(data = arc_inner,
                        aes(x0 = x0, y0 = y0, r0 = r0, r = r,
                            start = start, end = end, fill = label),
                        colour = 'white', linewidth = 0.5) +
  ggforce::geom_arc_bar(data = arc_outer,
                        aes(x0 = x0, y0 = y0, r0 = r0, r = r,
                            start = start, end = end, fill = label),
                        colour = 'white', linewidth = 0.3) +
  annotate('text', x = 0, y = 0, label = centre_label,
           family = 'Arial', size = 2.4, fontface = 'bold',
           colour = '#2171b5', lineheight = 0.9) +
  geom_segment(data = callout_df,
              aes(x = anchor_x, y = anchor_y, xend = label_x, yend = label_y),
              colour = 'grey50', linewidth = 0.25) +
  geom_text(data = callout_df,
           aes(x = label_x, y = label_y, label = callout_label, hjust = label_hjust),
           colour = callout_df$text_colour, size = 1.9, family = 'Arial',
           vjust = 0.5) +
  scale_fill_manual(values = all_colours) +
  coord_fixed(clip = 'off') +
  # Left side only needs to clear the donut itself -- every label (incl.
  # 'Remaining', anchored at its end angle) sits on the right now; right
  # side needs room for the label column + its longest text.
  xlim(-(r_outer_out + 0.3), r_outer_out + 5.8) +
  ylim(-(r_outer_out + 0.5), r_outer_out + 3.2) +
  theme_void(base_family = 'Arial') +
  theme(legend.position = 'none',
        plot.margin = margin(5, 5, 5, 5))

# Now a single ggplot (the side tableGrob legend was replaced by the
# on-wedge callouts above), so this uses the standard save_panel_png_pdf()
# convention rather than save_grid_png_pdf()'s gridExtra composite path.
#
# Sized for the Fig6 layout (A|B)/(C|D)/E: C shares a common row width with
# D (3.66in, half the usable A4 width) -- see
# Data_and_code/README_Fig5_6_ExtFig7_topics.md for the full per-panel size
# table.
save_panel_png_pdf(p_donut, path_fig6, 'f6c.new_route_donut',
                   width_in = 3.66, height_in = 3.4)
