#### Figure 6a — TF-set coupling per expressed enhancer vs |estimate| percentile ####
#
# Panel:   Figure 6a. For each expressed (tCRE) enhancer regulated by TFs at
#          both the chromatin (aCRE) and expression (tCRE) level, the two TF
#          sets are compared with the Jaccard index and bucketed into fully
#          uncoupled (Jaccard=0, disjoint TF sets) / intermediate / fully
#          coupled (Jaccard=1, identical TF sets) -- i.e. whether the same
#          TFs drive chromatin opening and transcription at that enhancer, or
#          whether the two layers of regulation are handled by different TFs.
#          Stacked bar shows how this 3-way split shifts as the per-stratum
#          |estimate| percentile cutoff (edge-strength stringency) is swept,
#          with total bar height tracking the shrinking number of enhancers
#          that remain eligible for the comparison at each cutoff.
# Reads:   Fig6/data/sweep_category_table.csv
#          (regenerated by
#           ../Data_and_code/threshold_sensitivity_sweep/build_sweep_data.R;
#           the shared plotting logic lives in
#           ../Data_and_code/threshold_sensitivity_sweep/plot_stacked_bar_height.R)
# Writes:  Fig6/out/f6a.stacked_TF_enhancer_estimate_pctl.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))
source(paste0(path_code, 'threshold_sensitivity_sweep/plot_stacked_bar_height.R'))

category_table <- read.csv(paste0(path_fig6_data, 'sweep_category_table.csv'))

p <- make_stacked_bar_linheight(category_table,
                                theme_name = 'TF_enhancer',
                                sweep_name = 'estimate_percentile')

# Sized for the Fig6 layout (A|B)/(C|D)/E: A shares a common row width with
# B (3.66in, half the usable A4 width) -- see
# Data_and_code/README_Fig5_6_ExtFig7_topics.md for the full per-panel size
# table.
save_panel_png_pdf(p, path_fig6, 'f6a.stacked_TF_enhancer_estimate_pctl',
                   width_in = 3.66, height_in = 3.4)
