#### Figure 6c — new-route donut chart for tCRE triplets ####
#
# Panel:   Fig 6c. Two-ring donut over all complete TF -> enhancer(tCRE) ->
#          promoter triplets. Inner ring: new route (TF/promoter pair absent
#          from the aCRE-only network) vs shared with the aCRE network. Outer
#          ring: the top 10 TFs contributing new-route triplets, remainder
#          collapsed into "Other TFs", with the shared slice carried through
#          unchanged. A text legend (tableGrob) beside it gives each slice's
#          share of new-route and of all triplets. Answers: when an enhancer's
#          own transcriptional activity is modelled explicitly, how much of
#          the resulting TF-enhancer-promoter regulatory structure was
#          invisible to a chromatin-accessibility-only view of the genome?
# Reads:   Fig6/data/triplets_tCRE.csv
#          (regenerated by
#           ../Data_and_code/tCRE_topology/build_tCRE_topology_data.R)
# Writes:  Fig6/out/f6c.new_route_donut.{png,pdf}
#
# Saved via save_grid_png_pdf() rather than save_panel_png_pdf() because the
# figure is a gridExtra::grid.arrange() composite of a ggplot and a tableGrob,
# not a single ggplot object ggsave() can serialize.
#
# Expected numbers: 3,929 total triplets, 90.3% new route, 9.7% shared,
# "Other TFs" = 72.1% of new-route triplets.

library(ggplot2)
library(ggforce)
library(gridExtra)

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

triplets_tCRE <- read.csv(paste0(path_fig6_data, 'triplets_tCRE.csv'))

#### Inner ring: new-route vs shared ####

n_new    <- sum(triplets_tCRE$new_route)
n_shared <- sum(!triplets_tCRE$new_route)
n_total  <- nrow(triplets_tCRE)

message('Triplets: ', n_total, '  new route ', round(100 * n_new / n_total, 1),
        '%  shared ', round(100 * n_shared / n_total, 1), '%')

inner_df <- data.frame(
  label = c('New route\n(tCRE only)', 'Shared with\naCRE network'),
  count = c(n_new, n_shared),
  frac  = c(n_new / n_total, n_shared / n_total)
)

#### Outer ring: top 10 TFs in new-route triplets ####

top_n_tfs     <- 10
tf_new_counts <- sort(table(triplets_tCRE$TF[triplets_tCRE$new_route]), decreasing = TRUE)
top_tfs       <- names(tf_new_counts)[seq_len(min(top_n_tfs, length(tf_new_counts)))]
n_top         <- as.integer(tf_new_counts[top_tfs])
n_other_new   <- n_new - sum(n_top)

outer_new_df <- data.frame(
  label    = c(top_tfs, 'Other TFs'),
  count    = c(n_top, n_other_new),
  category = 'new_route'
)
outer_shared_df <- data.frame(
  label    = 'Shared with\naCRE network',
  count    = n_shared,
  category = 'shared'
)
outer_df      <- rbind(outer_new_df, outer_shared_df)
outer_df$frac <- outer_df$count / n_total

message('  Other TFs: ', round(100 * n_other_new / n_new, 1), '% of new-route')

#### Colours ####

tf_colours    <- colorRampPalette(c('#08519c', '#6baed6'))(length(top_tfs) + 1)
outer_colours <- c(tf_colours, 'grey85')
names(outer_colours) <- c(top_tfs, 'Other TFs', 'Shared with\naCRE network')
inner_colours <- c('New route\n(tCRE only)'    = '#2171b5',
                   'Shared with\naCRE network' = 'grey85')
all_colours   <- c(inner_colours, outer_colours)

#### Legend rows ####

inner_legend_df <- data.frame(
  legend_label = paste0(inner_df$label, '  ', round(100 * inner_df$frac, 1),
                        '% of all triplets'),
  colour       = unname(inner_colours[inner_df$label]),
  stringsAsFactors = FALSE
)
outer_legend_df <- outer_new_df
outer_legend_df$pct_of_total    <- round(100 * outer_legend_df$count / n_total, 1)
outer_legend_df$pct_of_newroute <- round(100 * outer_legend_df$count / n_new,   1)
outer_legend_df$legend_label    <- paste0('  ', outer_legend_df$label, '  ',
                                          outer_legend_df$pct_of_newroute,
                                          '% of new-route (',
                                          outer_legend_df$pct_of_total, '% of all)')
outer_legend_df$colour <- unname(outer_colours[outer_legend_df$label])
outer_legend_df <- rbind(outer_legend_df[outer_legend_df$label != 'Other TFs', ],
                         outer_legend_df[outer_legend_df$label == 'Other TFs', ])
legend_df <- rbind(inner_legend_df,
                   outer_legend_df[, c('legend_label', 'colour')])

#### Arcs ####
# Angles start at the top (pi/2) and proceed clockwise.

make_arc_df <- function(fracs, labels, r0, r1) {
  end_ang   <- pi/2 - cumsum(fracs) * 2 * pi
  start_ang <- c(pi/2, head(end_ang, -1))
  data.frame(
    x0 = 0, y0 = 0, r0 = r0, r = r1,
    start = start_ang, end = end_ang,
    mid   = (start_ang + end_ang) / 2,
    label = labels, frac = fracs,
    stringsAsFactors = FALSE
  )
}

r_inner_in <- 1.5; r_inner_out <- 2.4
r_outer_in <- 2.6; r_outer_out <- 3.5

arc_inner <- make_arc_df(inner_df$frac, inner_df$label, r_inner_in, r_inner_out)
arc_outer <- make_arc_df(outer_df$frac, outer_df$label, r_outer_in, r_outer_out)

p_donut <- ggplot() +
  ggforce::geom_arc_bar(data = arc_inner,
                        aes(x0 = x0, y0 = y0, r0 = r0, r = r,
                            start = start, end = end, fill = label),
                        colour = 'white', linewidth = 0.5) +
  ggforce::geom_arc_bar(data = arc_outer,
                        aes(x0 = x0, y0 = y0, r0 = r0, r = r,
                            start = start, end = end, fill = label),
                        colour = 'white', linewidth = 0.3) +
  scale_fill_manual(values = all_colours) +
  coord_fixed() +
  xlim(-(r_outer_out + 1.2), r_outer_out + 1.2) +
  ylim(-(r_outer_out + 1.2), r_outer_out + 1.2) +
  labs(title = 'tCRE triplets: new routes vs shared with aCRE network',
       subtitle = paste0('Inner ring: new-route vs shared  |  ',
                         'Outer ring: top ', top_n_tfs,
                         ' TFs in new-route triplets')) +
  theme_void(base_family = 'Arial') +
  theme(legend.position = 'none',
        plot.title    = element_text(family = 'Arial', hjust = 0.5, size = 7,
                                     face = 'bold', colour = 'black'),
        plot.subtitle = element_text(family = 'Arial', hjust = 0.5, size = 6,
                                     colour = 'grey40'),
        plot.margin   = margin(5, 0, 5, 0))

legend_grob <- tableGrob(
  data.frame(TF = legend_df$legend_label),
  rows = NULL, cols = NULL,
  theme = ttheme_minimal(
    core = list(
      fg_params = list(col = legend_df$colour, hjust = 0, x = 0.02,
                       fontsize = 6, fontfamily = 'Arial', fontface = 'plain'),
      bg_params = list(fill = NA, col = NA)
    )
  )
)

# Canvas sized at 3600 x 2200 px at 300 dpi, with the donut and legend
# panels split 2200 : 1400 px.
save_grid_png_pdf(
  function() gridExtra::grid.arrange(p_donut, legend_grob,
                                     ncol = 2, widths = c(2200, 1400)),
  path_fig6, 'f6c.new_route_donut',
  width_in = 6.0, height_in = 3.67)
