#### Figure 6b — elastic-net-selected edges per enhancer by distance bin ####
#
# Panel:   Fig 6b. Mean elastic-net-selected Enhancer_promoter edges per enhancer in
#          50 kb enhancer-promoter distance bins, expressed vs non-expressed
#          enhancers, in the WITH-tCRE network. Pool-size corrected: every
#          base-network enhancer in the bin contributes, those with no
#          selected edge contributing 0 -- so an apparent enrichment in
#          expressed enhancers cannot simply be an artefact of the
#          non-expressed pool containing many low-signal enhancers that were
#          never candidates for an edge in the first place.
# Reads:   Fig6/data/distance_bin_with_tCRE.csv
#          (regenerated by
#           ../Data_and_code/tCRE_topology/build_tCRE_topology_data.R, shared
#           with ExtFig6c, which computes the same quantity on the
#           without-tCRE network)
# Writes:  Fig6/out/f6b.edges_per_enhancer_distance_bin.{png,pdf}
#
# Bins with fewer than 10 enhancers are dropped to avoid displaying noisy
# per-enhancer averages from very small bins.

library(ggplot2)
library(dplyr)

primary_folder <- '[primary_folder]'
path_fig6_data <- paste0(primary_folder, 'Fig6/data/')
path_fig6      <- paste0(primary_folder, 'Fig6/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

bin_df <- read.csv(paste0(path_fig6_data, 'distance_bin_with_tCRE.csv'))
bin_df$dist_bin <- factor(bin_df$dist_bin, levels = unique(bin_df$dist_bin))

f6b <- ggplot(bin_df %>% filter(n_enhancers >= 10),
              aes(x = dist_bin, y = y_mean,
                  colour = source_class, group = source_class)) +
  geom_line(linewidth = 0.4) +
  geom_point(aes(size = n_enhancers)) +
  scale_colour_manual(name = '',
                      values = c('expressed enhancers'     = 'darkorange',
                                 'non-expressed enhancers' = 'steelblue')) +
  scale_size_continuous(name = 'N enhancers', range = c(0.5, 2.5)) +
  scale_x_discrete(name = 'Enhancer-promoter distance bin (kb)') +
  scale_y_continuous(name = 'Mean elastic-net-selected edges per enhancer') +
  # No title -- the panel letter + figure caption identify it.
  bimodal_theme +
  theme(axis.text.x      = element_text(angle = 45, hjust = 1),
        legend.position  = 'bottom',
        legend.box       = 'vertical',
        legend.key.size  = unit(0.25, 'cm'),
        panel.grid.major = element_line(colour = 'grey92'))

# Sized for the Fig6 layout (A|B)/(C|D)/E: B shares a common row width with
# A (3.66in, half the usable A4 width) -- see
# Data_and_code/README_Fig5_6_ExtFig7_topics.md for the full per-panel size
# table.
save_panel_png_pdf(f6b, path_fig6, 'f6b.edges_per_enhancer_distance_bin',
                   width_in = 3.66, height_in = 3.4)
