#### Extended Figure 7b — TF-TF UMAP, direct vs indirect edge dominance ####
#
# Panel:   Ext Fig 7b. Two-panel ggraph plot on a fixed UMAP layout (from the
#          combined TF-TF regulatory association matrix): left panel shows
#          only direct (TF->promoter(TF)) edges, right panel shows only
#          indirect (TF->enhancer->promoter(TF)) edges; node colour =
#          outgoing-edge dominance category (Direct-dominant / Indirect-
#          dominant / Mixed / No outgoing edges), node size = reverse
#          PageRank (influence as a target of other TFs), top 5 TFs per
#          category labelled. Since both panels share the same fixed layout,
#          a TF's position is identical across panels, making it easy to see
#          which TFs shift from acting mostly through direct promoter binding
#          to acting mostly through intermediate enhancers.
# Reads:   ExtFig7/data/tf_umap_dominance.rds
#          (regenerated by ../Data_and_code/tf_tf_umap/build_tf_umap_data.R)
# Writes:  ExtFig7/out/ext_f7b.tf_umap_dominance.{png,pdf}

primary_folder <- '[primary_folder]'
path_extfig7_data <- paste0(primary_folder, 'ExtFig7/data/')
path_extfig7       <- paste0(primary_folder, 'ExtFig7/out/')
path_code          <- paste0(primary_folder, 'Data_and_code/')

library(ggraph)
library(igraph)
library(patchwork)
library(ggplot2)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

d <- readRDS(paste0(path_extfig7_data, 'tf_umap_dominance.rds'))

layout_all        <- d$layout_all
edge_direct       <- d$edge_direct
edge_indirect     <- d$edge_indirect
node_names        <- d$node_names
umap_fixed        <- d$umap_fixed
num_label_per_cat <- d$num_label_per_cat
dom_colours       <- d$dom_colours

# Labels: top num_label_per_cat TFs per dominance category by combined PageRank
tfs_to_label_all <- unlist(lapply(
  c('Direct-dominant', 'Indirect-dominant', 'Mixed'),
  function(cat) {
    idx <- which(layout_all$dominance == cat)
    if (length(idx) == 0) return(character(0))
    idx_top <- idx[order(layout_all$pr[idx], decreasing = TRUE)[
      seq_len(min(num_label_per_cat, length(idx)))]]
    node_names[idx_top]
  }
))

make_dom_panel <- function(layout, edge_df_panel, tfs_label, title_str) {
  edge_lims <- if (nrow(edge_df_panel) > 0)
    c(quantile(edge_df_panel$value, 0.1), quantile(edge_df_panel$value, 0.9))
  else c(0, 1)
  g_panel <- igraph::graph_from_data_frame(edge_df_panel,
                                           vertices = data.frame(name = node_names))
  lay <- ggraph::create_layout(g_panel, layout = umap_fixed[node_names, ])
  lay$pr        <- layout$pr
  lay$dominance <- layout$dominance
  ggraph(graph = lay) +
    geom_edge_diagonal(aes(width = value), color = 'grey75', alpha = 0.4) +
    scale_edge_width_continuous(range = c(0.01, 0.3), limits = edge_lims) +
    geom_node_point(aes(size = pr, colour = dominance), alpha = 0.85) +
    geom_node_text(aes(label = name, filter = name %in% tfs_label),
                   size = 1.8, repel = TRUE, family = 'Arial') +
    scale_colour_manual(name = 'Evidence type', values = dom_colours, drop = FALSE) +
    scale_size_continuous(name = 'Reverse\nPageRank') +
    theme_graph(background = 'white', base_family = 'Arial', base_size = 6) +
    theme(legend.position = 'right',
          legend.text  = element_text(family = 'Arial', size = 5),
          legend.title = element_text(family = 'Arial', size = 6),
          plot.title   = element_text(family = 'Arial', size = 7, face = 'bold')) +
    labs(title = title_str)
}

p_panel_direct   <- make_dom_panel(layout_all, edge_direct,   tfs_to_label_all,
                                   'Direct edges only\n(TF → promoter(TF))')
p_panel_indirect <- make_dom_panel(layout_all, edge_indirect, tfs_to_label_all,
                                   'Indirect edges only\n(TF → enhancer → promoter(TF))')

# No overall figure title/subtitle -- the panel letter + figure caption
# identify it (the caption carries the dominance-category thresholds and
# labelling rule previously stated in the dropped subtitle). The two
# per-subplot titles ("Direct edges only"/"Indirect edges only") are kept,
# since they are the only thing distinguishing the left/right UMAPs, same
# convention as Fig6d/Ext Fig6e's kept internal sub-titles.
ext_f7b <- (p_panel_direct | p_panel_indirect) +
  plot_layout(guides = 'collect')

# Sized for the Ext Fig 7 layout A/B: both panels span the full usable A4
# width (~7.47in) on their own row.
save_panel_png_pdf(ext_f7b, path_extfig7, 'ext_f7b.tf_umap_dominance',
                   width_in = 7.47, height_in = 3.6)
