#### Extended Figure 7a — Enhancer-promoter epigenomic feature enrichment (collapsed) ####
#
# Panel:   Ext Fig 7a. Dot-plot heatmap of whether pairs of epigenomic
#          features (H3K27ac, H3K27me3, stage-specific super-enhancer
#          membership, CpG islands, TATA boxes) co-occur more or less often
#          than expected between an enhancer and the promoter(s) it regulates
#          in the GRN: fill = odds ratio, size = -log10(adj. p), significant
#          pairs (FDR<=0.05) outlined in black. 3 sub-panels stratify by
#          enhancer subset (All enhancers / Expressed enhancers / Mediating
#          enhancers); promoter-collapsed variant (one row/column per
#          promoter, not per individual enhancer-promoter edge).
# Reads:   ExtFig7/data/ep_enrichment_collapsed.csv
#          (regenerated by
#           ../Data_and_code/ep_enrichment/build_ep_enrichment_data.R)
# Writes:  ExtFig7/out/ext_f7a.ep_enrichment_collapsed.{png,pdf}

primary_folder <- '[primary_folder]'
path_extfig7_data <- paste0(primary_folder, 'ExtFig7/data/')
path_extfig7       <- paste0(primary_folder, 'ExtFig7/out/')
path_code          <- paste0(primary_folder, 'Data_and_code/')

library(ggplot2)
library(dplyr)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

significance_threshold <- 0.05

res_collapsed <- read.csv(paste0(path_extfig7_data, 'ep_enrichment_collapsed.csv'),
                          stringsAsFactors = FALSE)

feature_display <- c(
  any.27ac_enhancer  = 'H3K27ac',   any.27ac_promoter  = 'H3K27ac',
  any.27m3_enhancer  = 'H3K27me3',  any.27m3_promoter  = 'H3K27me3',
  iPSC_SE_enhancer   = 'iPSC SE',   iPSC_SE_promoter   = 'iPSC SE',
  NSC_SE_enhancer    = 'NSC SE',    NSC_SE_promoter    = 'NSC SE',
  Neuron_SE_enhancer = 'Neuron SE', Neuron_SE_promoter = 'Neuron SE',
  CGI_enhancer       = 'CGI',       CGI_promoter       = 'CGI',
  TATA_box_enhancer  = 'TATA box',  TATA_box_promoter  = 'TATA box'
)
feature_levels  <- c('H3K27ac', 'H3K27me3', 'iPSC SE', 'NSC SE', 'Neuron SE', 'CGI', 'TATA box')
stratum_display <- c(all = 'All enhancers', tCRE_all = 'Expressed enhancers',
                     mediating = 'Mediating enhancers')

min_pval <- min(res_collapsed$adjpvalue[res_collapsed$adjpvalue > 0], na.rm = TRUE)

res_plot <- res_collapsed %>%
  mutate(
    adjpvalue   = ifelse(adjpvalue == 0, min_pval / 2, adjpvalue),
    log10p      = -log10(adjpvalue),
    significant = adjpvalue <= significance_threshold & !is.na(adjpvalue),
    odds_ratio  = ifelse(!significant, NA_real_, odds_ratio),
    log10p      = ifelse(!significant, NA_real_, log10p),
    enhancer    = factor(dplyr::recode(enhancer, !!!feature_display), levels = feature_levels),
    promoter    = factor(dplyr::recode(promoter, !!!feature_display), levels = rev(feature_levels)),
    stratum     = factor(dplyr::recode(stratum, !!!stratum_display),
                         levels = unname(stratum_display))
  )

ext_f7a <- ggplot(res_plot, aes(x = enhancer, y = promoter)) +
  geom_point(aes(size = log10p, fill = odds_ratio, colour = significant),
             shape = 21, stroke = 0.5) +
  geom_text(aes(label = ifelse(significant, round(odds_ratio, 2), '')),
            size = 1.6, colour = 'black', fontface = 'bold',
            nudge_y = 0.35, vjust = 0, family = 'Arial') +
  scale_fill_gradient2(name = 'Odds ratio',
                       low = 'blue', mid = 'white', high = 'red',
                       midpoint = 1, na.value = 'grey92') +
  scale_colour_manual(name = 'Significant',
                      values = c('FALSE' = 'grey80', 'TRUE' = 'black'),
                      guide  = 'none') +
  scale_size_continuous(name = '-log10(adj. p)', range = c(1, 5)) +
  facet_wrap(~stratum) +
  bimodal_theme +
  theme(
    axis.text.x      = element_text(angle = 45, hjust = 1, vjust = 1),
    panel.grid.major = element_line(colour = 'grey92'),
    legend.key.size  = unit(0.25, 'cm')
  ) +
  labs(x = 'Enhancer feature', y = 'Promoter feature')

# No title -- the panel letter + figure caption identify it.
#
# Sized for the Ext Fig 7 layout A/B: both panels span the full usable A4
# width (~7.47in) on their own row.
save_panel_png_pdf(ext_f7a, path_extfig7, 'ext_f7a.ep_enrichment_collapsed',
                   width_in = 7.47, height_in = 2.8)
