#### Extended Figure 7b — TF-TF UMAP, direct vs indirect edge dominance ####
#
# Panel:   Ext Fig 7b. Three-panel ggraph plot on a fixed UMAP layout (from
#          the combined TF-TF regulatory association matrix): left panel
#          shows only direct (TF->promoter(TF)) edges, middle panel shows
#          only indirect (TF->enhancer->promoter(TF)) edges, right panel
#          shows the combined edge set (per TF pair, whichever of the
#          direct/indirect weight is stronger); node colour = outgoing-edge
#          dominance category (Direct-dominant / Indirect-dominant / Mixed /
#          No outgoing edges), node size = reverse PageRank (influence as a
#          target of other TFs), top 5 TFs per category labelled. Since all
#          three panels share the same fixed layout, a TF's position is
#          identical across panels, making it easy to see which TFs shift
#          from acting mostly through direct promoter binding to acting
#          mostly through intermediate enhancers.
# Reads:   ExtFig7/data/tf_umap_dominance.rds
#          (regenerated by ../Data_and_code/tf_tf_umap/build_tf_umap_data.R)
# Writes:  ExtFig7/out/ext_f7b.tf_umap_dominance.{png,pdf}

primary_folder <- '[primary_folder]'
path_extfig7_data <- paste0(primary_folder, 'ExtFig7/data/')
path_extfig7       <- paste0(primary_folder, 'ExtFig7/out/')
path_code          <- paste0(primary_folder, 'Data_and_code/')

library(ggraph)
library(igraph)
library(patchwork)
library(ggplot2)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

d <- readRDS(paste0(path_extfig7_data, 'tf_umap_dominance.rds'))

layout_all        <- d$layout_all
edge_direct       <- d$edge_direct
edge_indirect     <- d$edge_indirect
edge_combined     <- d$edge_combined
node_names        <- d$node_names
umap_fixed        <- d$umap_fixed
num_label_per_cat <- d$num_label_per_cat
dom_colours       <- d$dom_colours

# Labels: top num_label_per_cat TFs per dominance category by combined PageRank
tfs_to_label_all <- unlist(lapply(
  c('Direct-dominant', 'Indirect-dominant', 'Mixed'),
  function(cat) {
    idx <- which(layout_all$dominance == cat)
    if (length(idx) == 0) return(character(0))
    idx_top <- idx[order(layout_all$pr[idx], decreasing = TRUE)[
      seq_len(min(num_label_per_cat, length(idx)))]]
    node_names[idx_top]
  }
))

# Legend kept on every sub-plot (rather than built once from a throwaway
# plot) and then collected into one shared bottom legend via
# plot_layout(guides = 'collect') below -- collecting requires each
# sub-plot to actually carry the guide, and 'drop = FALSE' on the colour
# scale below is what keeps all 4 dominance categories in that collected
# legend even though not every category necessarily appears with a
# non-zero-degree node in every one of the three edge subsets.
make_dom_panel <- function(layout, edge_df_panel, tfs_label, title_str) {
  edge_lims <- if (nrow(edge_df_panel) > 0)
    c(quantile(edge_df_panel$value, 0.1), quantile(edge_df_panel$value, 0.9))
  else c(0, 1)
  g_panel <- igraph::graph_from_data_frame(edge_df_panel,
                                           vertices = data.frame(name = node_names))
  lay <- ggraph::create_layout(g_panel, layout = umap_fixed[node_names, ])
  lay$pr        <- layout$pr
  lay$dominance <- layout$dominance
  ggraph(graph = lay) +
    geom_edge_diagonal(aes(width = value), color = 'grey75', alpha = 0.4) +
    scale_edge_width_continuous(range = c(0.01, 0.3), limits = edge_lims, guide = 'none') +
    geom_node_point(aes(size = pr, colour = dominance), alpha = 0.85) +
    geom_node_text(aes(label = name, filter = name %in% tfs_label),
                   size = 1.8, repel = TRUE, family = 'Arial') +
    # Node size range halved from ggplot2's default c(1, 6) to c(0.5, 3) --
    # the default made nodes too large relative to the fixed UMAP layout.
    scale_size_continuous(name = 'Reverse\nPageRank', range = c(0.5, 3)) +
    # override.aes doubles the colour legend's own key-swatch size (2.5,
    # up from geom_node_point's own smallest rendered node size) without
    # touching the halved node sizes actually drawn in the plot above --
    # the legend swatches were hard to distinguish at the plotted size.
    scale_colour_manual(name = 'Dominance category', values = dom_colours, drop = FALSE) +
    guides(colour = guide_legend(override.aes = list(size = 2.5))) +
    theme_graph(background = 'white', base_family = 'Arial', base_size = 6) +
    theme(legend.text  = element_text(family = 'Arial', size = 5),
          legend.title = element_text(family = 'Arial', size = 6),
          plot.title   = element_text(family = 'Arial', size = 7, face = 'bold')) +
    labs(title = title_str)
}

# Plain ASCII arrows ('->') rather than the Unicode '→' glyph: ggraph's
# theme_graph() text elements do not reliably resolve that glyph against
# the Arial subset embedded by cairo_pdf/ragg in this rendering path (it
# falls back to an ellipsis), unlike plain ggplot2 text geoms elsewhere in
# this repo (e.g. fig5a_sankey.R's on-plot labels) where the same glyph
# renders fine.
p_panel_direct   <- make_dom_panel(layout_all, edge_direct,   tfs_to_label_all,
                                   'Direct edges only\n(TF -> promoter(TF))')
p_panel_indirect <- make_dom_panel(layout_all, edge_indirect, tfs_to_label_all,
                                   'Indirect edges only\n(TF -> enhancer -> promoter(TF))')
p_panel_combined <- make_dom_panel(layout_all, edge_combined, tfs_to_label_all,
                                   'Combined edges\n(stronger of direct/indirect per pair)')

# No overall figure title/subtitle -- the panel letter + figure caption
# identify it (the caption carries the dominance-category thresholds and
# labelling rule that would otherwise need a subtitle). The three
# per-subplot titles ("Direct edges only"/"Indirect edges only"/"Combined
# edges") are kept, since they are the only thing distinguishing the three
# UMAPs, same convention as Fig6d/Ext Fig6e's kept internal sub-titles.
# Legend collected once at the bottom (not per sub-plot on the right) so
# all three UMAPs get more width on the page.
ext_f7b <- (p_panel_direct | p_panel_indirect | p_panel_combined) +
  plot_layout(guides = 'collect') &
  theme(legend.position = 'bottom', legend.box = 'vertical')

# Sized for the Ext Fig 7 layout A/B: both panels span the full usable A4
# width (~7.47in) on their own row.
save_panel_png_pdf(ext_f7b, path_extfig7, 'ext_f7b.tf_umap_dominance',
                   width_in = 7.47, height_in = 3.6)
