#### Extended Figure 5e/f — TF-set coupling per promoter vs adjpvalue / dev_ratio ####
#
# Panel:   Extended Figure 5, panels e and f combined into one image (the
#          panel letters are added manually during figure composition, not
#          drawn by this script). For each promoter with both a chromatin
#          (aCRE) and an expression (tCRE) measurement reachable by a TF,
#          the two TF sets are compared with the Jaccard index and bucketed
#          into fully uncoupled (Jaccard=0, disjoint TF sets) / intermediate
#          / fully coupled (Jaccard=1, identical TF sets). Left sub-panel
#          (former e): shift as the adjpvalue significance threshold is
#          swept. Right sub-panel (former f): shift as the dev_ratio (model
#          fit quality) threshold is swept. Both share one legend (they use
#          the exact same 3 categories/colours) -- keeping them as two
#          separate images with two identical legends was redundant.
# Reads:   Fig5/data/sweep_category_table.csv
#          (regenerated by
#           ../Data_and_code/threshold_sensitivity_sweep/build_sweep_data.R;
#           the shared plotting logic lives in
#           ../Data_and_code/threshold_sensitivity_sweep/plot_stacked_bar_height.R)
# Writes:  Fig5/out/ext_f5ef.stacked_TF_promoter_coupling.{png,pdf}
#
# No in-bar percentage labels (show_labels = FALSE on both sub-panels): at
# these threshold ranges, 2+ of the 3 categories can be simultaneously tiny
# within the same bar, which no per-segment label placement stayed
# collision-free for after several attempts -- see
# plot_stacked_bar_height.R's show_labels doc. Exact percentages belong in
# the figure caption instead.

primary_folder <- '[primary_folder]'
path_fig5_data <- paste0(primary_folder, 'Fig5/data/')
path_fig5      <- paste0(primary_folder, 'Fig5/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

library(patchwork)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))
source(paste0(path_code, 'threshold_sensitivity_sweep/plot_stacked_bar_height.R'))

category_table <- read.csv(paste0(path_fig5_data, 'sweep_category_table.csv'))

p_e <- make_stacked_bar_linheight(category_table,
                                  theme_name  = 'TF_promoter',
                                  sweep_name  = 'adjpvalue_threshold',
                                  show_labels = FALSE) +
  theme(legend.position = 'none')

p_f <- make_stacked_bar_linheight(category_table,
                                  theme_name  = 'TF_promoter',
                                  sweep_name  = 'dev_ratio_threshold',
                                  show_labels = FALSE) +
  theme(legend.position = 'none')

# guides = 'collect' + a single bottom legend.position (set via `&`, which
# applies to every sub-plot including the patchwork-level guide, unlike
# `+` which would only touch the last one) pools the two sub-plots'
# identical legends into one shared legend instead of dropping both --
# both p_e/p_f already have their own legend suppressed above, so this is
# the ONLY legend in the combined image.
ext_f5ef <- (p_e | p_f) +
  plot_layout(guides = 'collect') &
  theme(legend.position  = 'bottom',
        legend.key.size  = unit(0.25, 'cm'),
        legend.direction = 'vertical')

# Sized for the Ext Fig 5 layout (A|B)/C/(D|E|F): the combined e/f image
# takes the same column width the two would have spanned together as
# separate D/E/F-style panels (2 x 2.39in + gutter), with height matching
# D's own row height -- see Data_and_code/README_Fig5_6_ExtFig7_topics.md
# for the full per-panel size table.
save_panel_png_pdf(ext_f5ef, path_fig5, 'ext_f5ef.stacked_TF_promoter_coupling',
                   width_in = 4.93, height_in = 2.6)

message('Done. Results written to: ', path_fig5)
