#### Extended Figure 5c (legend) — shared 8-network colour key ####
#
# Panel:   Ext Fig 5c (legend panel, "C2" in the (C1|C2)/C3 arrangement
#          alongside the node-count and edge-count bar charts). A single
#          colour key for the 8 network variants (base vs elastic-net-
#          regularised, with/without TOBIAS footprinting, with/without Hi-C
#          contacts) used consistently across Ext Fig 5 panels A, B, C1 and
#          C3 -- built once here rather than repeated as an inline legend
#          on every panel that uses this colour scheme. Panel A has no
#          legend of its own (relies entirely on this one); panel B keeps
#          its own separate 2-entry linetype legend (with/without TOBIAS)
#          since that distinction isn't a colour and this legend can't
#          carry it.
# Reads:   Fig5/data/network_node_counts.csv
#          (regenerated by
#           ../Data_and_code/network_basic_stats/build_network_composition_data.R;
#           read here only for its network/colour mapping, not its values --
#           any of that regeneration step's output files would give the
#           same mapping, this one is arbitrary)
# Writes:  Fig5/out/ext_f5c.network_legend.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig5_data <- paste0(primary_folder, 'Fig5/data/')
path_fig5      <- paste0(primary_folder, 'Fig5/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

library(ggplot2)
library(cowplot)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

d <- read.csv(paste0(path_fig5_data, 'network_node_counts.csv'))

network_levels <- c('Base', 'Base, no TOBIAS', 'Base, no Hi-C', 'Base, no Hi-C, no TOBIAS',
                    'Elastic net', 'Elastic net, no TOBIAS', 'Elastic net, no Hi-C',
                    'Elastic net, no Hi-C, no TOBIAS')
d$network <- factor(d$network, levels = network_levels)

display_colors <- setNames(d$colour, d$network)[network_levels]
display_colors <- display_colors[!is.na(display_colors)]

# A minimal dummy plot exists only to generate a legend via the same
# scale_fill_manual() mapping C1/C3 use -- its data/geom/axes are never
# rendered, only the legend grob is kept (via cowplot::get_legend()) and
# saved on its own.
legend_source_plot <- ggplot(d, aes(x = network, y = value, fill = network)) +
  geom_bar(stat = 'identity') +
  scale_fill_manual(name = 'Network', values = display_colors,
                    guide = guide_legend(ncol = 2)) +
  bimodal_theme +
  theme(legend.position   = 'right',
        legend.key.size   = unit(0.3, 'cm'),
        legend.title      = element_text(face = 'bold'))

ext_f5c_legend <- cowplot::get_legend(legend_source_plot)
ext_f5c_legend <- cowplot::ggdraw(ext_f5c_legend)

# Sized for the Ext Fig 5 layout (A|B)/C/(D|E|F), specifically the C row's
# (C1|C2)/C3 sub-arrangement: C2 sits beside C1 (the node-count bars), sized
# just wide enough for the two-column "Base.../Elastic net..." legend text
# at 5-7pt Arial, with C1+C2's shared row height matching C1's own natural
# height -- see Data_and_code/README_Fig5_6_ExtFig7_topics.md for the full
# per-panel size table.
save_panel_png_pdf(ext_f5c_legend, path_fig5, 'ext_f5c.network_legend',
                   width_in = 3.6, height_in = 1.4)

message('Done. Results written to: ', path_fig5)
