#### Extended Figure 5d — network-tier ABC concordance (F1) ####
#
# Panel:   Ext Fig 5d. F1 between network-edge membership and ABC
#          (Activity-by-Contact) positivity, at each of three GRN
#          construction stages — base (every proximity/Hi-C-eligible
#          candidate pair, before model fitting), elastic_net (edges kept by
#          the elastic-net model, before the standard confidence filters),
#          and filtered (the final published high-confidence GRN) — one
#          line per ABC score variant (three cell types plus their per-pair
#          maximum). Both F1 and its restriction universe (which candidate
#          pairs ABC actually evaluated) are computed against ABC's full,
#          unfiltered score matrix, so absence of an ABC score means "ABC
#          never evaluated this pair," not "ABC scored it below threshold."
#          Rising F1 across tiers indicates that elastic-net selection and
#          the standard filters both increase agreement with this
#          independent, orthogonal regulatory map, beyond what a
#          no-selection floor achieves.
# Reads:   Fig5/data/tier_comparison.csv
#          (regenerated by
#           ../Data_and_code/abc_validation/copy_tier_comparison.R)
# Writes:  Fig5/out/ext_f5d.abc_tier_comparison_f1.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig5_data <- paste0(primary_folder, 'Fig5/data/')
path_fig5      <- paste0(primary_folder, 'Fig5/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

library(ggplot2)
library(dplyr)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

tier_comparison <- read.csv(paste0(path_fig5_data, 'tier_comparison.csv'), stringsAsFactors = FALSE)

tier_levels <- c('base', 'elastic_net', 'filtered')
tier_labels <- c(base = 'Base', elastic_net = 'Elastic net', filtered = 'Filtered')

variant_labels <- c(iPSC = 'iPSC', NSC = 'NSC', Neuron = 'Neuron',
                    max_across_celltypes = 'Max across cell types')
variant_colors <- c(iPSC = '#6BAED6', NSC = '#74C476', Neuron = '#FC8D59',
                    `max_across_celltypes` = '#252525')

tier_comparison <- tier_comparison %>%
  mutate(tier = factor(dplyr::recode(tier, !!!tier_labels), levels = unname(tier_labels)),
         abc_variant = factor(dplyr::recode(abc_variant, !!!variant_labels),
                              levels = unname(variant_labels)))
display_colors <- setNames(variant_colors, variant_labels[names(variant_colors)])

ext_f5d <- ggplot(tier_comparison, aes(x = tier, y = f1, colour = abc_variant, group = abc_variant)) +
  geom_line(linewidth = 0.5) +
  geom_point(size = 1.2) +
  scale_x_discrete(name = 'Network tier') +
  scale_y_continuous(name = 'F1 (ABC positivity vs network edge)') +
  scale_colour_manual(name = 'ABC variant', values = display_colors) +
  ggtitle('ABC concordance across network tiers') +
  bimodal_theme +
  theme(legend.position = 'bottom',
        legend.key.size = unit(0.25, 'cm'))

save_panel_png_pdf(ext_f5d, path_fig5, 'ext_f5d.abc_tier_comparison_f1',
                   width_in = 3.2, height_in = 3.0)
