#### Extended Figure 5b — eQTL validation F1 curves ####
#
# Panel:   Ext Fig 5b. F1 score vs dev_ratio threshold, one line per network
#          variant (8 total, light=base/dark=lasso): how well each network's
#          enhancer-to-promoter edges recover known enhancer-to-gene links
#          from fine-mapped eQTLs, pooled across all source/target
#          measurement-type combinations ('All interactions'). TOBIAS
#          footprinting only affects TF-to-peak edges, which this
#          enhancer-to-promoter-only metric never touches -- so each
#          variant is numerically IDENTICAL to its '..., no TOBIAS' pair
#          (confirmed directly against eqtl_f1_all_interactions.csv: the 4
#          pairs' F1 values match to full float precision at every
#          dev_ratio grid point). Colour alone would draw these as one
#          perfectly overlapping line per pair; linetype (solid = with
#          TOBIAS, dashed = no TOBIAS) keeps both legend entries visibly
#          traceable even though only 4 distinct curves are actually drawn.
# Reads:   Fig5/data/eqtl_f1_all_interactions.csv
#          (regenerated by
#           ../Data_and_code/chipseq_eqtl_validation/build_eqtl_f1_data.R)
# Writes:  Fig5/out/ext_f5b.eqtl_F1_all_interactions.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig5_data <- paste0(primary_folder, 'Fig5/data/')
path_fig5      <- paste0(primary_folder, 'Fig5/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

library(ggplot2)
library(dplyr)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

results <- read.csv(paste0(path_fig5_data, 'eqtl_f1_all_interactions.csv'))

network_labels <- c(
  base                   = 'Base',
  base_no_tobias         = 'Base, no TOBIAS',
  base_no_hic            = 'Base, no Hi-C',
  base_no_hic_no_tobias  = 'Base, no Hi-C, no TOBIAS',
  lasso                  = 'Lasso',
  lasso_no_tobias        = 'Lasso, no TOBIAS',
  lasso_no_hic           = 'Lasso, no Hi-C',
  lasso_no_hic_no_tobias = 'Lasso, no Hi-C, no TOBIAS'
)
network_levels <- unname(network_labels)
networks_colors <- c(
  base                   = '#6BAED6',
  base_no_tobias         = '#FC8D59',
  base_no_hic            = '#74C476',
  base_no_hic_no_tobias  = '#BCBDDC',
  lasso                  = '#08519C',
  lasso_no_tobias        = '#B30000',
  lasso_no_hic           = '#238B45',
  lasso_no_hic_no_tobias = '#6A51A3'
)
display_colors <- setNames(networks_colors, network_labels[names(networks_colors)])

# Linetype keyed on the TOBIAS flag so the 4 colour-identical pairs (see note
# above) are still distinguishable: solid = with TOBIAS, dashed = no TOBIAS.
network_linetypes <- setNames(
  ifelse(grepl('no_tobias', names(network_labels)), 'dashed', 'solid'),
  network_labels)

results <- results %>%
  mutate(network = factor(dplyr::recode(network, !!!network_labels), levels = network_levels))

ext_f5b <- ggplot(results, aes(x = dev_ratio, y = value,
                               color = network, linetype = network)) +
  geom_line(linewidth = 0.5) +
  scale_x_continuous(name = 'Deviance ratio threshold',
                     breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)) +
  scale_y_continuous(name = 'F1 score') +
  scale_color_manual(name = 'Network', values = display_colors) +
  scale_linetype_manual(name = 'Network', values = network_linetypes) +
  ggtitle('eQTL validation (all interactions)') +
  bimodal_theme +
  theme(legend.position = 'bottom',
        legend.key.size = unit(0.25, 'cm'),
        legend.key.width = unit(0.5, 'cm'),
        legend.direction = 'vertical',
        axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1))

save_panel_png_pdf(ext_f5b, path_fig5, 'ext_f5b.eqtl_F1_all_interactions',
                   width_in = 3.2, height_in = 3.0)
