#### Extended Figure 5a — ChIP-seq validation F1 curves ####
#
# Panel:   Ext Fig 5a. F1 score vs dev_ratio threshold, one line per network
#          variant (8 total, light=base/dark=lasso), faceted by TF
#          (TEAD4, ONECUT2). An inferred edge counts as recovered whether it
#          reaches the TF's ChIP-seq target directly (TF->peak) or indirectly
#          through an intermediate enhancer (TF->enhancer->peak), pooling
#          promoter and enhancer targets together.
# Reads:   Fig5/data/chipseq_f1_either_all.csv
#          (regenerated by
#           ../Data_and_code/chipseq_eqtl_validation/build_chipseq_f1_data.R)
# Writes:  Fig5/out/ext_f5a.chipseq_F1_either_all.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig5_data <- paste0(primary_folder, 'Fig5/data/')
path_fig5      <- paste0(primary_folder, 'Fig5/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

library(ggplot2)
library(dplyr)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

res <- read.csv(paste0(path_fig5_data, 'chipseq_f1_either_all.csv'))

network_labels <- c(
  base                   = 'Base',
  base_no_tobias         = 'Base, no TOBIAS',
  base_no_hic            = 'Base, no Hi-C',
  base_no_hic_no_tobias  = 'Base, no Hi-C, no TOBIAS',
  lasso                  = 'Lasso',
  lasso_no_tobias        = 'Lasso, no TOBIAS',
  lasso_no_hic           = 'Lasso, no Hi-C',
  lasso_no_hic_no_tobias = 'Lasso, no Hi-C, no TOBIAS'
)
network_levels <- unname(network_labels)
networks_colors <- c(
  base                   = '#6BAED6',
  base_no_tobias         = '#FC8D59',
  base_no_hic            = '#74C476',
  base_no_hic_no_tobias  = '#BCBDDC',
  lasso                  = '#08519C',
  lasso_no_tobias        = '#B30000',
  lasso_no_hic           = '#238B45',
  lasso_no_hic_no_tobias = '#6A51A3'
)
display_colors <- setNames(networks_colors, network_labels[names(networks_colors)])

res <- res %>%
  mutate(network = factor(dplyr::recode(network, !!!network_labels), levels = network_levels))

ext_f5a <- ggplot(res, aes(x = dev_ratio, y = value, color = network)) +
  geom_line(linewidth = 0.5) +
  facet_wrap(~TF, scales = 'free') +
  scale_x_continuous(name = 'Deviance ratio threshold',
                     breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)) +
  scale_y_continuous(name = 'F1 score') +
  scale_color_manual(name = 'Network', values = display_colors) +
  ggtitle('ChIP-seq validation (either connection, all targets)') +
  bimodal_theme +
  theme(legend.position = 'bottom',
        legend.key.size = unit(0.25, 'cm'),
        legend.direction = 'vertical',
        axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1))

save_panel_png_pdf(ext_f5a, path_fig5, 'ext_f5a.chipseq_F1_either_all',
                   width_in = 4.5, height_in = 3.2)
