#### Extended Figure 5c (edges) — network edge counts across variants ####
#
# Panel:   Ext Fig 5c (edge panel). Bar chart of edge counts (total, TF-peak,
#          TF-promoter, TF-enhancer, enhancer-promoter) across all 8 network
#          variants (base vs elastic-net-regularised, with/without TOBIAS
#          footprinting, with/without Hi-C contacts), free y-scale per facet
#          so each edge-count metric is readable regardless of its overall
#          magnitude.
# Reads:   Fig5/data/network_edge_counts.csv
#          (regenerated by
#           ../Data_and_code/network_basic_stats/build_network_composition_data.R)
# Writes:  Fig5/out/ext_f5c.network_edge_counts.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig5_data <- paste0(primary_folder, 'Fig5/data/')
path_fig5      <- paste0(primary_folder, 'Fig5/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

library(ggplot2)

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

d <- read.csv(paste0(path_fig5_data, 'network_edge_counts.csv'))

edge_levels <- c('Number of edges', 'Number of TF-to-peak edges',
                 'Number of TF-to-promoter edges', 'Number of TF-to-enhancer edges',
                 'Number of enhancer-to-promoter edges')
d$metric <- factor(d$metric, levels = edge_levels)
network_levels <- c('Base', 'Base, no TOBIAS', 'Base, no Hi-C', 'Base, no Hi-C, no TOBIAS',
                    'Lasso', 'Lasso, no TOBIAS', 'Lasso, no Hi-C', 'Lasso, no Hi-C, no TOBIAS')
d$network <- factor(d$network, levels = network_levels)

display_colors <- setNames(d$colour, d$network)[network_levels]
display_colors <- display_colors[!is.na(display_colors)]

ext_f5c_edges <- ggplot(d, aes(x = network, y = value, fill = network)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~metric, scales = 'free', ncol = 5) +
  scale_fill_manual(values = display_colors) +
  ggtitle('Network edge counts') +
  bimodal_theme +
  theme(legend.position = 'none',
        axis.text.x  = element_text(angle = 45, vjust = 0.9, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

save_panel_png_pdf(ext_f5c_edges, path_fig5, 'ext_f5c.network_edge_counts',
                   width_in = 7.0, height_in = 2.0)
