#### Figure 5b — clustered heatmap of TF cumulative effects ####
#
# Panel:   Fig 5b. ComplexHeatmap of column-scaled signed TF cumulative
#          effects across 4 columns (mediating enhancer aCRE/tCRE, promoter
#          aCRE/tCRE) -- how much each TF's regulatory activity, summed
#          across all its edges, shifts each target class -- rows split into
#          6 clusters (activator-like vs repressor-like, with activator-like
#          TFs further split into sub-clusters), right annotation = log
#          rank-product bar (an overall importance ranking across all 4
#          columns).
# Reads:   Fig5/data/tf_effects_clustering.rds
#          (regenerated by
#           ../Data_and_code/tf_effects_clustering/build_tf_effects_data.R,
#           shared with Fig5c)
# Writes:  Fig5/out/f5b.heatmap_TF_effects.{png,pdf}
#
# Font note: ComplexHeatmap has no single "everything in Arial" switch, so the
# family is set per component via gpar(fontfamily='Arial') on the annotations,
# the legends and the heatmap title, and the device family is set to Arial by
# save_grid_png_pdf(). Row and column names are not shown (too many TFs and
# target columns to label individually), so the only visible text is
# legend/annotation text, kept at 5-6 pt.

library(ComplexHeatmap)
library(circlize)
library(grid)

primary_folder <- '[primary_folder]'
path_fig5_data <- paste0(primary_folder, 'Fig5/data/')
path_fig5      <- paste0(primary_folder, 'Fig5/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

d <- readRDS(paste0(path_fig5_data, 'tf_effects_clustering.rds'))

sh             <- d$sh
sh_sqrt        <- d$sh_sqrt
rk             <- d$rk
row_group_fine <- d$row_group_fine
col_order      <- d$col_order
cdend          <- d$cdend
stat_label     <- d$stat_label

sqrt_signed <- function(x) sqrt(abs(x)) * sign(x)

# colour scale on the scaled values, centred at 0
col_fun <- colorRamp2(
  c(quantile(sh, 0.025, na.rm = TRUE), 0, quantile(sh, 0.975, na.rm = TRUE)),
  c('blue', 'white', 'red')
)

# column annotation: measurement type (aCRE/tCRE) nested under target class
col_anno_df <- data.frame(
  target      = c('Mediating Enhancer', 'Mediating Enhancer', 'Promoter', 'Promoter'),
  measurement = c('aCRE', 'tCRE', 'aCRE', 'tCRE'),
  row.names   = col_order
)
col_anno_colors <- list(
  target      = c('Promoter' = '#4DAF4A', 'Mediating Enhancer' = '#984EA3'),
  measurement = c(aCRE = '#377EB8', tCRE = '#E41A1C')
)
ha_col <- HeatmapAnnotation(
  measurement = col_anno_df$measurement,
  target      = col_anno_df$target,
  col         = col_anno_colors,
  annotation_name_side  = 'left',
  annotation_name_gp    = gpar(fontfamily = 'Arial', fontsize = 6),
  annotation_legend_param = list(
    measurement = list(title_gp  = gpar(fontfamily = 'Arial', fontsize = 6),
                       labels_gp = gpar(fontfamily = 'Arial', fontsize = 5)),
    target      = list(title_gp  = gpar(fontfamily = 'Arial', fontsize = 6),
                       labels_gp = gpar(fontfamily = 'Arial', fontsize = 5))
  ),
  simple_anno_size = unit(2.5, 'mm')
)

# row annotation: log rank-product bar
ha_row <- rowAnnotation(
  logRP = anno_barplot(rk, border = FALSE,
                       gp = gpar(col = 'grey50', fill = 'grey50'),
                       axis_param = list(gp = gpar(fontfamily = 'Arial', fontsize = 5))),
  annotation_name_gp = gpar(fontfamily = 'Arial', fontsize = 6),
  width = unit(8, 'mm')
)

# Display sh (scaled); cluster on sh_sqrt (compressed) within each split group.
ht <- Heatmap(sh,
  name                     = paste0('Scaled TF effect\n[', stat_label, ']'),
  col                      = col_fun,
  row_split                = row_group_fine,
  cluster_columns          = cdend,
  cluster_rows             = TRUE,
  clustering_distance_rows = function(m) dist(sqrt_signed(m)),
  clustering_method_rows   = 'ward.D2',
  top_annotation           = ha_col,
  right_annotation         = ha_row,
  show_row_names           = FALSE,
  show_column_names        = FALSE,
  row_title_gp             = gpar(fontfamily = 'Arial', fontsize = 6),
  column_title_gp          = gpar(fontfamily = 'Arial', fontsize = 7),
  heatmap_legend_param     = list(
    title_gp      = gpar(fontfamily = 'Arial', fontsize = 6),
    labels_gp     = gpar(fontfamily = 'Arial', fontsize = 5),
    grid_width    = unit(3, 'mm'),
    legend_height = unit(15, 'mm')
  )
)

save_grid_png_pdf(function() draw(ht),
                  path_fig5, 'f5b.heatmap_TF_effects',
                  width_in = 3.0, height_in = 6.4)
