#### Figure 5d — TF-set coupling per promoter vs |estimate| percentile ####
#
# Panel:   Fig 5d. For each promoter with both a chromatin (aCRE) and an
#          expression (tCRE) measurement reachable by a TF, the two TF sets
#          are compared with the Jaccard index and bucketed into fully
#          uncoupled (Jaccard=0, disjoint TF sets) / intermediate / fully
#          coupled (Jaccard=1, identical TF sets). Stacked bar shows how
#          this 3-way split shifts as the per-stratum |estimate| percentile
#          cutoff (edge-strength stringency) is swept, with total bar height
#          tracking the shrinking number of promoters that remain eligible
#          for the comparison at each cutoff.
# Reads:   Fig5/data/sweep_category_table.csv
#          (regenerated by
#           ../Data_and_code/threshold_sensitivity_sweep/build_sweep_data.R;
#           the shared plotting logic lives in
#           ../Data_and_code/threshold_sensitivity_sweep/plot_stacked_bar_height.R)
# Writes:  Fig5/out/f5d.stacked_TF_promoter_estimate_pctl.{png,pdf}

primary_folder <- '[primary_folder]'
path_fig5_data <- paste0(primary_folder, 'Fig5/data/')
path_fig5      <- paste0(primary_folder, 'Fig5/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))
source(paste0(path_code, 'threshold_sensitivity_sweep/plot_stacked_bar_height.R'))

category_table <- read.csv(paste0(path_fig5_data, 'sweep_category_table.csv'))

f5d <- make_stacked_bar_linheight(category_table,
                                  theme_name = 'TF_promoter',
                                  sweep_name = 'estimate_percentile')

save_panel_png_pdf(f5d, path_fig5, 'f5d.stacked_TF_promoter_estimate_pctl',
                   width_in = 3.2, height_in = 3.0)
