#### Figure 5c — TF characteristics dot plot ####
#
# Panel:   Fig 5c. Dot-plot heatmap of Welch t-tests linking each TF's
#          cumulative regulatory effect (6 target x modality strata) to each
#          known TF property (activator, repressor, pioneer, closer,
#          ATAC+/-, RNA+/-). Fill = mean difference, size = -log10(FDR),
#          black outline = FDR <= significance_threshold. Answers: do TFs
#          annotated as e.g. pioneer factors have systematically stronger (or
#          weaker) cumulative effects on a given target class than TFs
#          without that annotation?
# Reads:   Fig5/data/tf_effects_clustering.rds
#          (regenerated by
#           ../Data_and_code/tf_effects_clustering/build_tf_effects_data.R,
#           shared with Fig5b)
#          Fig5/data/TF_grouping_by_chromvar_correlation_and_literature.tsv
#          (TF role annotation table)
# Writes:  Fig5/out/f5c.TF_characteristics_dotplot.{png,pdf}
#
# Dot-plot style note: shape = 21 with stroke = 0.8 so the significance
# outline is a real border on the dot rather than a separate mark.

library(tidyverse)

primary_folder <- '[primary_folder]'
path_fig5_data <- paste0(primary_folder, 'Fig5/data/')
path_fig5      <- paste0(primary_folder, 'Fig5/out/')
path_code      <- paste0(primary_folder, 'Data_and_code/')

source(paste0(path_code, 'network_loading/plot_theme_and_save.R'))

significance_threshold <- 0.1   # FDR cutoff for the black significance outline

d <- readRDS(paste0(path_fig5_data, 'tf_effects_clustering.rds'))
h_wide      <- d$h_wide
rk          <- d$rk
row_group   <- d$row_group
results_bar <- d$results_bar

#### TF characteristics table ####

tf_characteristics <- read.table(
  paste0(path_fig5_data, 'TF_grouping_by_chromvar_correlation_and_literature.tsv'),
  header = TRUE, check.names = FALSE)

tf_characteristics <- tf_characteristics[
  !grepl('::', tf_characteristics$motifName, fixed = TRUE), ]
tf_characteristics$motifName <- toupper(tf_characteristics$motifName)
tf_characteristics <- unique(tf_characteristics[,
  c('motifName', 'TF_activator', 'TF_repressor', 'TF_pioneer',
    'TF_closer', 'ATAC+', 'ATAC-', 'RNA+', 'RNA-')])
colnames(tf_characteristics) <- gsub('+', 'plus',  colnames(tf_characteristics), fixed = TRUE)
colnames(tf_characteristics) <- gsub('-', 'minus', colnames(tf_characteristics), fixed = TRUE)

to_remove_motifs <- tf_characteristics$motifName[
  duplicated(tf_characteristics$motifName)]
tf_characteristics <- tf_characteristics[
  !(tf_characteristics$motifName %in% to_remove_motifs), ]

#### TF-level statistics table ####

all_peaks_wide <- results_bar[['All']] %>%
  select(source, target_measurement_type, log_total_effect) %>%
  mutate(col = paste0('all_peaks_', target_measurement_type)) %>%
  select(source, col, log_total_effect) %>%
  pivot_wider(names_from = col, values_from = log_total_effect) %>%
  column_to_rownames('source') %>%
  as.matrix()

common_tfs <- intersect(rownames(h_wide), rownames(all_peaks_wide))
tf_statistics <- data.frame(
  h_wide[common_tfs, ],
  all_peaks_wide[common_tfs, ],
  logRP                = rk[common_tfs],
  dominant_effect_sign = row_group[common_tfs],
  motifName            = toupper(common_tfs)
)

tf_df <- merge(tf_statistics, tf_characteristics, by = 'motifName', all = FALSE)
message('TFs matched to characteristics table: ', nrow(tf_df))

#### Welch t-test per (TF effect x TF characteristic) ####

cont_vars <- c('mediating_enhancer_aCRE', 'mediating_enhancer_tCRE',
               'promoter_aCRE', 'promoter_tCRE',
               'all_peaks_aCRE', 'all_peaks_tCRE')
tf_char_names <- setdiff(colnames(tf_characteristics), 'motifName')

char_results <- data.frame(
  expand.grid(TF_effect = cont_vars, TF_characteristic = tf_char_names),
  diff   = NA_real_,
  pvalue = NA_real_
)
for (iter in seq_len(nrow(char_results))) {
  ef  <- as.character(char_results$TF_effect[iter])
  ch  <- as.character(char_results$TF_characteristic[iter])
  tmp <- t.test(as.formula(paste0('`', ef, '` ~ `', ch, '`')), data = tf_df)
  char_results$diff[iter]   <- tmp$estimate[2] - tmp$estimate[1]
  char_results$pvalue[iter] <- tmp$p.value
}
char_results$qvalue      <- p.adjust(char_results$pvalue, method = 'fdr')
char_results$adjpval     <- -log10(char_results$qvalue)
char_results$significant <- char_results$qvalue <= significance_threshold

message('Significant (FDR <= ', significance_threshold, '): ',
        sum(char_results$significant), ' of ', nrow(char_results))

#### Dot plot ####

x_labels <- c(
  mediating_enhancer_aCRE = 'Mediating enh. (ATAC)',
  mediating_enhancer_tCRE = 'Mediating enh. (TSS)',
  promoter_aCRE           = 'Promoter (ATAC)',
  promoter_tCRE           = 'Promoter (TSS)',
  all_peaks_aCRE          = 'All peaks (ATAC)',
  all_peaks_tCRE          = 'All peaks (TSS)'
)
y_labels <- c(
  TF_activator = 'Activator',
  TF_repressor = 'Repressor',
  TF_pioneer   = 'Pioneer',
  TF_closer    = 'Closer',
  ATACplus     = 'ATAC+',
  ATACminus    = 'ATAC-',
  RNAplus      = 'RNA+',
  RNAminus     = 'RNA-'
)

char_results$x_lab <- factor(x_labels[as.character(char_results$TF_effect)],
                             levels = x_labels)
char_results$y_lab <- factor(y_labels[as.character(char_results$TF_characteristic)],
                             levels = rev(y_labels))

f5c <- ggplot(char_results,
              aes(x = x_lab, y = y_lab,
                  fill = diff, colour = significant, size = adjpval)) +
  geom_point(shape = 21, stroke = 0.4) +
  scale_x_discrete(name = 'TF cumulative effect on...') +
  scale_y_discrete(name = 'TF characteristic') +
  scale_colour_manual(name = 'Significant',
                      values = c('FALSE' = 'grey80', 'TRUE' = 'black')) +
  scale_fill_gradient2(name = 'Average\nDifference',
                       low = 'blue', mid = 'white', high = 'red', midpoint = 0) +
  # range bumped from the original c(1, 4.5) now that this panel has more
  # vertical room in the Fig5 (A/C/D)|B layout (see the save call below) --
  # dot size is an absolute mm range, not proportional to canvas size, so it
  # needs its own increase to actually use the extra space rather than just
  # leaving it as blank row spacing.
  scale_size_continuous(name = '-log10(adj. p)', range = c(1.3, 5.5)) +
  bimodal_theme +
  theme(axis.text.x      = element_text(angle = 45, hjust = 1, vjust = 1),
        panel.grid.major = element_line(colour = 'grey92'),
        legend.key.size  = unit(0.3, 'cm'))

# Sized for the Fig5 layout (A/C/D)|B: shares its column width (3.4in) with
# panels A and D, and is taller than its own minimal content size to use
# the extra vertical room left in the A+C+D height budget (summing to B's
# 9.5in) -- see Data_and_code/README_Fig5_6_ExtFig7_topics.md for the full
# per-panel size table. The extra height gives this 8x6 dot grid more
# breathing room (larger dots, more space between rows) rather than sitting
# unused as padding.
save_panel_png_pdf(f5c, path_fig5, 'f5c.TF_characteristics_dotplot',
                   width_in = 3.4, height_in = 3.80)
